### ISSUE TITLE
Issue with importing pdfplumber library

### ISSUE THREAD

**Issue by FatemaD1577** [jsvine/pdfplumber#1033]
## Describe the bug

I have installed the pdfplumber library from https://pypi.org/project/pdfplumber/. The installation is done successfully. But when I try to import the library it gives me error.

## Have you tried [repairing](https://github.com/jsvine/pdfplumber/blob/stable/docs/repairing.md) the PDF?

*Please try running your code with `pdfplumber.open(..., repair=True)` before submitting a bug report.*

## Code to reproduce the problem

*Paste it here, or attach a Python file.*

## PDF file

*Please attach any PDFs necessary to reproduce the problem.*

*If you need to redact text in a sensitive PDF, you can run it through [JoshData/pdf-redactor](https://github.com/JoshData/pdf-redactor).*

## Expected behavior

*What did you expect the result __should__ have been?*

## Actual behavior

*What actually happened, instead?*

## Screenshots

*If applicable, add screenshots to help explain your problem.*

## Environment

- pdfplumber version: [e.g., 0.5.22]
- Python version: [e.g., 3.8.1]
- OS: [e.g., Mac, Linux, etc.]

## Additional context

*Add any other context/notes about the problem here.*

I am getting error while importing the library as follows:
ImportError: cannot import name 'PDFStackT' from 'pdfminer.pdfinterp'

**Comment by jsvine** [comment]
Hi @FatemaD1577; it appears you have an old version of `pdfminer` or `pdfminer.six` installed. This should fix it for you:

```
pip uninstall pdfminer
pip uninstall pdfminer.six
pip install -U pdfplumber
```

**Comment by FatemaD1577** [comment]
Hi @jsvine . Thanks for the reply. I tried the steps but still facing the same issue.

**Comment by yifan-chen-2020** [comment]
> 

> Hi @FatemaD1577; it appears you have an old version of `pdfminer` or `pdfminer.six` installed. This should fix it for you:
> 
> ```
> pip uninstall pdfminer
> pip uninstall pdfminer.six
> pip install -U pdfplumber
> ```
The solution above solves the following error:

`ImportError: cannot import name 'PDFStackT' from 'pdfminer.pdfinterp' (/home/tiger/.local/lib/python3.9/site-packages/pdfminer/pdfinterp.py)
`

**Comment by FatemaD1577** [comment]
> > 
> 
> > Hi @FatemaD1577; it appears you have an old version of `pdfminer` or `pdfminer.six` installed. This should fix it for you:
> > ```
> > pip uninstall pdfminer
> > pip uninstall pdfminer.six
> > pip install -U pdfplumber
> > ```
> 
> The solution above solves the following error:
> 
> `ImportError: cannot import name 'PDFStackT' from 'pdfminer.pdfinterp' (/home/tiger/.local/lib/python3.9/site-packages/pdfminer/pdfinterp.py) `

Didn't solve the issue at my end.

![image](https://github.com/jsvine/pdfplumber/assets/107674241/9b99f0ad-5b7f-48a3-bb9d-c148e6eaee4c)

**Comment by gengdata** [comment]
> > > 
> > 
> > 
> > > Hi @FatemaD1577; it appears you have an old version of `pdfminer` or `pdfminer.six` installed. This should fix it for you:
> > > ```
> > > pip uninstall pdfminer
> > > pip uninstall pdfminer.six
> > > pip install -U pdfplumber
> > > ```
> > 
> > 
> > The solution above solves the following error:
> > `ImportError: cannot import name 'PDFStackT' from 'pdfminer.pdfinterp' (/home/tiger/.local/lib/python3.9/site-packages/pdfminer/pdfinterp.py) `
> 
> Didn't solve the issue at my end.
> 
> ![image](https://private-user-images.githubusercontent.com/107674241/279344302-9b99f0ad-5b7f-48a3-bb9d-c148e6eaee4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzQ4OTksIm5iZiI6MTcwOTEzNDU5OSwicGF0aCI6Ii8xMDc2NzQyNDEvMjc5MzQ0MzAyLTliOTlmMGFkLTViN2YtNDhhMy1iYjlkLWMxNDhlNmVhZWU0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQxNTM2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmQwNmYyMGMxMGVmMTgzYWU5ODgyMGEyM2U2ZjQwMDViMjM1NzI1OGNhYTI1OGY0ZTUwMzQxMWRhODNhODIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WLWllraxduIex3DXXlIh55p1GqesI2w75b_3mllhuBs)

Restart the jupyternootbook page

**Comment by Jefronty** [comment]
> > > > 
> > > 
> > > 
> > > > Hi @FatemaD1577; it appears you have an old version of `pdfminer` or `pdfminer.six` installed. This should fix it for you:
> > > > ```
> > > > pip uninstall pdfminer
> > > > pip uninstall pdfminer.six
> > > > pip install -U pdfplumber
> > > > ```
> > > 
> > > 
> > > The solution above solves the following error:
> > > `ImportError: cannot import name 'PDFStackT' from 'pdfminer.pdfinterp' (/home/tiger/.local/lib/python3.9/site-packages/pdfminer/pdfinterp.py) `
> > 
> > 
> > Didn't solve the issue at my end.
> > ![image](https://private-user-images.githubusercontent.com/107674241/279344302-9b99f0ad-5b7f-48a3-bb9d-c148e6eaee4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzQ4OTksIm5iZiI6MTcwOTEzNDU5OSwicGF0aCI6Ii8xMDc2NzQyNDEvMjc5MzQ0MzAyLTliOTlmMGFkLTViN2YtNDhhMy1iYjlkLWMxNDhlNmVhZWU0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQxNTM2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmQwNmYyMGMxMGVmMTgzYWU5ODgyMGEyM2U2ZjQwMDViMjM1NzI1OGNhYTI1OGY0ZTUwMzQxMWRhODNhODIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WLWllraxduIex3DXXlIh55p1GqesI2w75b_3mllhuBs)
> 
> Restart the jupyternootbook page

I also tried the suggested steps and it did not fix the issue.  I am using Python 3.9.2 on Debian 11 (Bullseye)

**Comment by optivisionlab** [comment]
> > 
> 
> > CHÀO@FatemaD1577`pdfminer`; có vẻ như bạn đã cài đặt phiên bản cũ `pdfminer.six`. Điều này sẽ khắc phục được lỗi cho bạn:
> > ```
> > pip uninstall pdfminer
> > pip uninstall pdfminer.six
> > pip install -U pdfplumber
> > ```
> 
> Giải pháp trên giải quyết được lỗi sau:
> 
> `ImportError: cannot import name 'PDFStackT' from 'pdfminer.pdfinterp' (/home/tiger/.local/lib/python3.9/site-packages/pdfminer/pdfinterp.py) `

It's worked
